services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    logging:
      driver: none

  redis:
    image: redis:7
    volumes:
      - redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
    logging:
      driver: none

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
      GITHUB_APP_SECRET_KEY: ${GITHUB_APP_SECRET_KEY}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle check || bundle install && bundle exec sidekiq"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
      - api
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
      GITHUB_APP_SECRET_KEY: ${GITHUB_APP_SECRET_KEY}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

volumes:
  postgres_data:
  redis_data:
  bundle_cache: