default: &default
  adapter: sqlite3
  encoding: unicode
  # Increase pool size to handle concurrent requests better
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # Add statement timeout to prevent long-running queries
  statement_timeout: 5000
  # Optimize prepared statements
  prepared_statements: true
  # Add connection validation to avoid stale connections
  checkout_timeout: 5
  idle_timeout: 300
  reaping_frequency: 10

development:
  <<: *default
  database: storage/development.sqlite3
  # Enable statement cache for development
  statement_cache: true

test:
  <<: *default
  database: storage/test.sqlite3
  # Disable prepared statements for testing to avoid leaks
  prepared_statements: false

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  # Production optimization settings
  statement_cache: true
  # Set minimum connections to keep warm
  min_connections: 5
  # Increase connection validation timeout for production
  checkout_timeout: 10