default: &default
  adapter: postgresql
  encoding: unicode
  # Increase pool size to handle concurrent requests better
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # Add statement timeout to prevent long-running queries
  statement_timeout: 5000
  # Optimize prepared statements
  prepared_statements: true
  # Add connection validation to avoid stale connections
  checkout_timeout: 5
  idle_timeout: 300
  reaping_frequency: 10

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://ideaboard:password@db:5432/ideaboard_development" } %>
  # Enable statement cache for development
  statement_cache: true

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_TEST_URL") { "postgres://ideaboard:password@db:5432/ideaboard_test" } %>
  # Disable prepared statements for testing to avoid leaks
  prepared_statements: false

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
  # Production optimization settings
  statement_cache: true
  # Set minimum connections to keep warm
  min_connections: 5
  # Increase connection validation timeout for production
  checkout_timeout: 10